import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import 'bootstrap/dist/css/bootstrap.css';
import 'bootstrap/dist/js/bootstrap';
import 'jquery/dist/jquery';
var app = document.createElement('div');
app.style.height = '100vh';
app.style.width = '100vw';
app.style.backgroundColor = 'black';
app.style.overflowX = 'hidden';
document.body.appendChild(app);
ReactDOM.render(<App />, app);
